name: "Drift Detection"

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/15 * * * *'

jobs:
  drift-detection:
    name: "drift-detection"
    uses: subhamay-bhattacharyya/9999-reusable-wf/.github/workflows/tf-drift-detection.yaml@main
    with:
      github-env: devl
      terraform-ver: ${{ vars.TERRAFORM_VERSION }}
      tfvar-file: devl.terraform.tfvars
      aws-region: ${{ vars.AWS_REGION }}
      aws-role-arn: ${{ vars.PROD_AWS_ROLE_ARN }}
      aws-tf-state-bucket-name: ${{ vars.PROD_AWS_TF_STATE_BUCKET_NAME }}
      kms-key-arn: ${{ vars.PROD_AWS_KMS_KEY_ARN }}
    secrets:
      git-token: ${{ secrets.GIT_TOKEN }}