name: "Run Infracost"

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  create:
    name: "run-infracost"
    uses: subhamay-bhattacharyya/9999-reusable-wf/.github/workflows/tf-infracost.yaml@main
    secrets:
      infracost-api-key: ${{ secrets.INFRACOST_API_KEY }}
